version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  groups:
    mix-minor-updates:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  groups:
    gh-actions:
      patterns:
      - "*"